export type EvidenceErrorCode =
  | "EVIDENCE_SOURCE_NOT_ALLOWED"
  | "EVIDENCE_SOURCE_NOT_FOUND"
  | "EVIDENCE_SOURCE_AMBIGUOUS"
  | "EVIDENCE_SOURCE_AUTHORITY_UNAVAILABLE"
  | "EVIDENCE_REGISTRATION_CONFLICT"
  | "EVIDENCE_CERTIFICATION_UNRECOGNIZED_AUTHORITY"
  | "EVIDENCE_CERTIFICATION_NOT_FOUND"
  | "EVIDENCE_CERTIFICATION_AUTHORITY_UNAVAILABLE"
  | "EVIDENCE_CERTIFICATION_SUBJECT_MISMATCH"
  | "EVIDENCE_CERTIFICATION_STATE_NOT_ADMISSIBLE"
  | "EVIDENCE_CERTIFICATION_RESOLUTION_INCONSISTENT"
  | "EVIDENCE_NOT_FOUND"
  | "EVIDENCE_TERMINAL"
  | "EVIDENCE_JOURNAL_CORRUPT"
  | "EVIDENCE_JOURNAL_UNAVAILABLE";

export class EvidenceDomainError extends Error {
  constructor(readonly code: EvidenceErrorCode, message: string, options?: ErrorOptions) {
    super(`${code}: ${message}`, options);
    this.name = "EvidenceDomainError";
  }
}
