export interface WorkDeliverableMetricFixture {
  label: string;
  value: string;
  tone?: 'success' | 'warning' | 'critical';
}

export interface WorkDeliverableHistoryFixture {
  version: string;
  date: string;
  description: string;
}

export interface WorkDeliverableDetailFixture {
  summary: string;
  whyItMatters: string;
  blocking: readonly string[];
  keyEvidence: readonly WorkDeliverableMetricFixture[];
  history: readonly WorkDeliverableHistoryFixture[];
  technicalDetails: readonly WorkDeliverableMetricFixture[];
}

export interface WorkDeliverableFixture {
  deliverableId: string;
  title: string;
  confidence: number;
  readinessLabel: string;
  publicationScore: number;
  alert: string;
  nextAction: string;
  progressTone: 'warning' | 'critical';
  detail?: WorkDeliverableDetailFixture;
}

export interface WorkDeliverablesFixture {
  workId: string;
  deliverables: readonly WorkDeliverableFixture[];
}

export const workDeliverablesFixtures: Record<string, WorkDeliverablesFixture> = {
  'work-001': {
    workId: 'work-001',
    deliverables: [
      {
        deliverableId: 'board-presentation',
        title: 'Q3 Budget Review — Board Presentation',
        confidence: 76,
        readinessLabel: 'Ready for publication',
        publicationScore: 64,
        alert: '3 unresolved comments in revenue section',
        nextAction: 'Resolve comments to reach publication readiness',
        progressTone: 'warning',
        detail: {
          summary:
            '3 comments block CFO review. CRM source missing — revenue figures provisional. Resolve comments and load CRM to reach publication readiness.',
          whyItMatters:
            'This deliverable is required for Board of Directors. Publication score is 64% — not yet ready for distribution.',
          blocking: [
            'CRM pipeline data for revenue section',
            'CFO sign-off pending',
          ],
          keyEvidence: [
            { label: 'Evidence coverage', value: '87%', tone: 'success' },
            { label: 'Completeness', value: '78%', tone: 'warning' },
            { label: 'Publication score', value: '64%', tone: 'warning' },
            { label: 'Pending comments', value: '3', tone: 'critical' },
            { label: 'Outstanding reviews', value: '1', tone: 'critical' },
          ],
          history: [
            { version: 'v1.2', date: '11 Jul', description: 'Sarah Chen comments incorporated' },
            { version: 'v1.1', date: '10 Jul', description: 'CFO section added' },
            { version: 'v1.0', date: '9 Jul', description: 'Initial NOVA draft' },
          ],
          technicalDetails: [
            { label: 'Generated by', value: 'NOVA' },
            { label: 'Reviewed by', value: 'Sarah Chen' },
            { label: 'Validated by', value: 'Not yet' },
            { label: 'Format', value: 'Presentation' },
            { label: 'Audience', value: 'Board of Directors' },
          ],
        },
      },
      {
        deliverableId: 'investment-summary',
        title: 'Infrastructure Investment Summary',
        confidence: 41,
        readinessLabel: 'Ready for publication',
        publicationScore: 31,
        alert: 'CRM source missing — revenue figures provisional',
        nextAction: 'Load CRM export and request Thomas Vidal validation',
        progressTone: 'critical',
      },
    ],
  },
};

export function getWorkDeliverablesFixture(workId: string) {
  return workDeliverablesFixtures[workId];
}
